### ISSUE TITLE
Implement Digest Authentication

### ISSUE THREAD

**Issue by chnrxn** [andygrunwald/go-gerrit#5]
Is there a plan for implementing Digest authentication?

**Comment by andygrunwald** [comment]
Thanks for your question @chnrxn.
I want to see Digest auth in go-gerrit, yes. There is a need for it.
A correct / detailed plan is not existing, because i implement these features mostly if i need them myself.
I only need to find time for it, but will be happy to support you or another contributer who is interested in implementing digest auth.

Is this an option for you?

**Comment by andygrunwald** [comment]
A side note for a future me: This can be helpful https://github.com/mattbaird/http-digest-auth-client

**Comment by andygrunwald** [comment]
@chnrxn Digest auth is now supported. Have a look at the README for a few examples :)
Have fun!
